services:
  postgres:
    container_name: postgres_news
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    env_file:
      - ../.env
    volumes:
      - pgdata_news:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - backend

networks:
  backend:
#    driver: bridge
    external: true

volumes:
  pgdata_news:
